quanLyGiay/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace quanLyGiay.Models
{
    [Table(" Users")]
    public class User
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public String FullName { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Phone { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        public string Password{ get; set; }

        public DateTime? Create_At { get; set; }

        public DateTime? Updated_At { get; set; }

    }
}

quanLyGiay/Areas/Admin/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanLyGiay.Models;

namespace quanLyGiay.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        private quanLyGiayDBContext db = new quanLyGiayDBContext();

        // GET: Admin/Order
        public ActionResult Index()
        {
            var list = db.Orders.ToList();
            return View(list);
        }

        // GET: Admin/Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Admin/Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                order.Create_At = DateTime.Now;
                order.Updated_At = DateTime.Now;
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Admin/Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Admin/Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Order order)
        {
            if (ModelState.IsValid)
            {
                order.Updated_At = DateTime.Now;
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Admin/Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Admin/Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanLyGiay/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using quanLyGiay.Models;

namespace quanLyGiay.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        private quanLyGiayDBContext db = new quanLyGiayDBContext();

        // GET: Admin/User
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Admin/User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Admin/User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( User user)
        {
            if (ModelState.IsValid)
            {
                user.Create_At = DateTime.Now;
                user.Updated_At = DateTime.Now;
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Admin/User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                user.Updated_At = DateTime.Now;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Admin/User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Admin/User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

quanLyGiay/Areas/Admin/Views/User/Create.cshtml
@model quanLyGiay.Models.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Thêm loại sản phẩm</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index","Order")" class="btn btn-sm btn-warning">
                        Quay lại danh sách
                    </a>
                    <input type="submit" value="Thêm" class="btn btn-success btn-sm" />
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <div class="row">
                <div class="col-md-9">
                    <div class="form-group">
                        <label>Tên nhân viên</label>
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label> Tên tài khoản của nhân viên </label>
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label> Mật khẩu của nhân viên </label>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3">

                    <div class="form-group">
                        <label>Số điện thoại</label>
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
        </div>

    </div>
}

quanLyGiay/Areas/Admin/Views/User/Delete.cshtml
@model quanLyGiay.Models.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Xác nhận xóa</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index", "User")" class="btn btn-sm btn-success">
                        Quay về danh sách
                    </a>
                    <input type="submit" value="Delete" class="btn btn-sm btn-danger" />
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <div class="alert alert-warning">
                <strong>Thông báo </strong> Bạn có muốn xóa thông tin khách hàng này không?
            </div>
            <dl class="dl-horizontal">
                <dt>
                    Họ tên nhân viên
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FullName)
                </dd>

                <dt>
                    Số điện thoại
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>

                <dt>
                    Email
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    Tên đăng nhập
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>

                <dt>
                    Mật khẩu đăng nhập
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Password)
                </dd>


                <dt>
                    Ngày lưu thông tin
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Create_At)
                </dd>

                <dt>
                    Ngày cập nhật gần nhất
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Updated_At)
                </dd>

            </dl>
        </div>

    </div>

}

quanLyGiay/Areas/Admin/Views/User/Details.cshtml
@model quanLyGiay.Models.User

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Thông tin khách hàng</strong>
                </div>

                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index", "User")" class="btn btn-sm btn-success">
                        Quay về danh sách
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <dl class="dl-horizontal">
                <dt>
                    Họ tên nhân viên
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FullName)
                </dd>

                <dt>
                    Số điện thoại
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>

                <dt>
                    Email
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    Tên đăng nhập
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>

                <dt>
                    Mật khẩu đăng nhập
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Password)
                </dd>

                <dt>
                    Ngày lưu thông tin
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Create_At)
                </dd>

                <dt>
                    Ngày cập nhật gần nhất
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Updated_At)
                </dd>

            </dl>
        </div>

    </div>

}

quanLyGiay/Areas/Admin/Views/User/Edit.cshtml
@model quanLyGiay.Models.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Create_At)
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Cập nhật thông tin khách</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index","User")" class="btn btn-sm btn-warning">
                        Quay lại danh sách
                    </a>
                    <input type="submit" value="Cập nhật" class="btn btn-success btn-sm" />
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <div class="row">
                <div class="col-md-9">
                    <div class="form-group">
                        <label>Tên khách hàng</label>
                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label> Tên tài khoản </label>
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label> Mật khẩu tài khoản </label>
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-3">

                    <div class="form-group">
                        <label>Số điện thoại</label>
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label>Email</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
        </div>
    </div>
}

quanLyGiay/Areas/Admin/Views/User/Index.cshtml
@model IEnumerable<quanLyGiay.Models.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Danh sách nhân viên</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Create","User")" class="btn btn-sm btn-success">
                    Thêm
                </a>
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <table class="table table-bUsered table-hover">
            <thead>
                <tr>
                    <th style="width:20px;" class="text-center">#</th>
                    <th style="width:20px;" class="text-center">STT</th>
                    <th>Họ tên</th>
                    <th style="width:100px;" class="text-center">SĐT</th>
                    <th style="width:100px;" class="text-center">Email</th>
                    <th style="width: 300px;" class="text-center">Chức năng</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td class="text-center">
                            <input name="CheckId" type="checkbox" />
                        </td>
                        <td class="text-center">@item.Id</td>
                        <td>@item.FullName</td>
                        <td class="text-center">@item.Phone</td>
                        <td class="text-center">@item.Email</td>
                        <td class="text-center" style="display:flex; justify-content:space-evenly;">
                            <a href="@Url.Action("Edit", "User", new { @id = item.Id})" class="btn btn-sm btn-info">
                                Sửa
                            </a>
                            <a href="@Url.Action("Details", "User", new { @id = item.Id})" class="btn btn-sm btn-warning">
                                Chi tiết
                            </a>
                            <a href="@Url.Action("Delete", "User", new { @id = item.Id})" class="btn btn-sm btn-danger">
                                Xóa
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>